### PR TITLE
feat: added `@parcel/css` support

### LINKED ISSUE #153: Feature request - parcel-css as custom minifier
### Feature Proposal
Allow [parcel-css](https://github.com/parcel-bundler/parcel-css) as custom minifier 

### Feature Use Case
We already support esbuild, so why not parcel-css

### PR DESCRIPTION
**Pull request by alexander-akait**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

fixes #153

### Breaking Changes

No

### Additional Info

- prefixes are broken and do not work
- minification is broken for special IE10/11 properties (i.e. `*prop: value`)
- collapsing properties are broken in some cases
- escaped things are broken

### CODE REVIEW

**Comment by devongovett** [comment]
This is cool to see! Thanks for doing this.

> minification is broken for special IE10/11 properties (i.e. *prop: value)

Still deciding what to do about this. See https://github.com/parcel-bundler/parcel-css/issues/39.

Could you explain more about the other issues you ran into? Were there broken code samples I could look at?

**Comment by alexander-akait** [comment]
@devongovett 

- prefixes are broken and do not work

I tried to set `chrome: 4` and use `border-radius` and unfortunately, no prefixes, tried it for `transition` and other properties popular properties, and prefixes just not outputted for all cases (also tried different targets), tried to use `browserslist_to_target`, it returns something weird (like `version`) and it still not work

- collapsing properties are broken in some cases

I run it on cssnano codebase and there a some cases, most around prefixes and normal writing, sorry, I don't have time to fully investigate it, try to adapt cssnano tests (quite possible there are cssnano bugs too), but they are mostly edge cases

> escaped things are broken

I was wrong to use here `broken`, sorry, for example:
```
    content: "a\
b";
```

Can be collapsed in one string, good examples:
```css
a::before {
    content: "This string is demarcated by double quotes.";
    content: 'This string is demarcated by single quotes.';
    content: "This is a string with \" an escaped double quote.";
    content: "This string also has \22 an escaped double quote.";
    content: 'This is a string with \' an escaped single quote.';
    content: 'This string also has \27 an escaped single quote.';
    content: "This is a string with \\ an escaped backslash.";
    content: "This string also has \22an escaped double quote.";
    content: "This string also has \22  an escaped double quote.";
    content: "This string has a \Aline break in it.";
    content: "A really long \
awesome string";
    content: ";'@ /**/\"";
    content: '\'"\\';
    content: "a\
b";
    content: "a\
b";
    content: "a\
b";
    content: "a\b";
    content: "a\
\
\
\\
b";
    content: 'a\62 c';
}

a[title="a not s\
o very long title"] {
    color: red;
}
a[title="a not so very long title"] {
    color: red;
}
```

**Comment by devongovett** [comment]
Thanks for the info!

I see prefixes for `border-radius` working in the [playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A262144%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20border-radius%3A%2024px%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D), but I'll try it out with the webpack plugin.

Haven't handled the `content` property yet, but those are good examples.

**Comment by alexander-akait** [comment]
@devongovett Maybe something wrong between JS and Rust, because I tried the same and no prefixes, usage:
```js
new CssMinimizerPlugin({
      minimizerOptions: {
        targets: {
          chrome: 4,
        },
        drafts: {
          nesting: true,
        },
      },
      minify: [CssMinimizerPlugin.parcelCssMinify],
}).apply(compiler);
```

Example without plugin:
```js
const parcelCss = require("@parcel/css");

async function test() {
  const parcelCssOptions = {
    minify: true,
    targets: { chrome: 4 },
    drafts: { nesting: true },
    sourceMap: true,
    filename: "foo.css",
    code: Buffer.from(".foo {border-radius: 24px;}"),
  };

  const result = await parcelCss.transform(parcelCssOptions);
  console.log(result.code.toString());
  // .foo{border-radius:24px}
}

test();
```

**Comment by devongovett** [comment]
Ah, I see the issue. For performance, targets are represented using a 24 bit number to represent `major.minor.patch` versions, so you have to use some bit shifting to make it work. See https://github.com/parcel-bundler/parcel-css#from-node. Maybe we can improve the API a bit to make this easier to understand, or add a util function for creating these versions.

```js
targets: {
  chrome: 4 << 16
}
```

**Comment by alexander-akait** [comment]
@devongovett Yep, feel free to improve this, I think it is out of scope plugin, don't think we should do it here

**Comment by devongovett** [comment]
Yup, definitely.

**Pull request merged**
