### PR TITLE
change `loaders` to `rules` in README

### PR DESCRIPTION
**Pull request by 0atman**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fix for the readme getting started code

### Breaking Changes

none

### Additional Info

I'm unsure why this would have happened, as I've not been following the development of webpack very closely.

### CODE REVIEW

**Comment by 0atman** [comment]
Forgive me if this is bogus, but I had to make this change while implementing this plugin.

**Comment by alexander-akait** [comment]
Can you accept CLA (in github actions)?

**Comment by 0atman** [comment]
@alexander-akait done!

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
