### PR TITLE
Feat: added defaults functions for `clean-css` and `csso`

### LINKED ISSUE #50: Set appropriate defaults for clean-css and csso
### Feature Proposal

Allow clean-css and csso to be set as configuration options, and appropriate defaults applied. It's quite convenient to use default of cssnano, where you just need to set the cssnano options. But if you want to use any of the alternatives, you need a lot of configuration to override the minify function as shown in readme. It could just be given as a config value or which minifier you want to use, and appropriate defaults set.

### LINKED ISSUE #62: Not working with 2 minimizers
- Operating System: n/a
- Node Version: 12 and 14 both
- NPM Version: latest 6.x
- webpack Version: 5.24.2
- css-minimizer-webpack-plugin Version: 1.2.0

### Expected Behavior

In https://github.com/facebook/docusaurus/pull/4089, we use 2 minimizers.  It appears that one of them isn't getting applied because the css has unexpectedly raised in size by 4kb.  Any support or thoughts would be appreciated.

### Actual Behavior

It doesn't appear to be performing the same optimization

### Code

See the code below this discussion https://github.com/facebook/docusaurus/pull/4089/files#r588305123

### How Do We Reproduce?

https://github.com/facebook/docusaurus/pull/4089
It worked with css-optimizer-webpack-plugin, now it doesn't

### PR DESCRIPTION
**Pull request by cap-Bernardito**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Fixes #50 
Fixes #62 

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by RDIL** [comment]
Cheers!

**Comment by slorber** [comment]
Thanks!

So the multiple minifiers array syntax was already supported as I understand right?

**Comment by alexander-akait** [comment]
No, it will be in v2 (release soon)

**Comment by slorber** [comment]
I see thanks, looks the array syntax is not released yet (https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/72)

> release soon

No hurry, just wondering what you mean by soon? 1 day / 1 week / 1 month?

**Comment by alexander-akait** [comment]
Hope this week

**Comment by alexander-akait** [comment]
We need review https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/78 and merge, after this we can do release, but I have very limited time :disappointed:

**Pull request merged**
