### PR TITLE
remove mini-css-extract-plugin from example webpack configuration

### LINKED ISSUE #65: Example webpack configuration is misleading
Documentation Is: very misleading

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Extremely misleading

### Please Explain in Detail...
If `mini-css-extract-plugin` is not required for this plugin to function, it should not be included in the example webpack configuration. Why? I was following this example configuration, and saw that I needed to `require` two packages: `mini-css-extract-plugin` and `css-minimizer-webpack-plugin`. I thought to myself, "ok, this is weird, shouldn't the css-minimizer-webpack-plugin already call mini-css-extract-plugin if its a dependency?" But, after attempting to build unsuccessfully, I found out that `mini-css-extract-plugin` is not a peerDependency, dependency, or devDependency of css-minimizer-webpack-plugin, ***meaning that I have to manually install it myself.*** At this point I was getting quite confused, and installed mini-css-extract-plugin, thinking it would further improve my file size. But lo and behold, the example configuration **does not even function!** Adding the `MiniCssExtractPlugin.loader` loader to my CSS section does nothing but make the plugin complain that I did not set it up properly. So I added mini-css-extract-plugin to my plugins list, and what does that do? Nothing but more errors regarding the abscense of `document`. I then uninstalled mini-css-extract-plugin to find that not using it at all does not affect the performance of css-minimizer-webpack-plugin. If mini-css-extract-plugin serves no purpose regarding this plugin, it should not have been mentioned at all in the example webpack configuration.

### Your Proposal for Changes
If mini-css-extract-plugin is not required for this plugin to work, it should not be mentioned in the example configuration. A suggestion to use this plugin may be good, but it should not be in the example configuration.

### PR DESCRIPTION
**Pull request by sportshead**
fixes #65

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
Makes things less confusing #65 

### Breaking Changes
None.

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Plugin will not work without extracting CSS

**Comment by sportshead** [comment]
> mini-css-extract-plugin is not required to working with this plugin
So are you saying it is required or not?

**Comment by alexander-akait** [comment]
It is required when you want to extract CSS, but you can copy CSS files using `copy-webpack-plugin` (just one example
)

**Comment by alexander-akait** [comment]
Yes, but popular usage with `mini-css-extract-plugin`, let's add comment about it, no need to remove

**Pull request closed without merging**
