### PR TITLE
Resolve security concerns in cssnano dependency tree

### PR DESCRIPTION
**Pull request by eFrane**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

I ran into a couple of security warnings related to `cssnano` and subsequent transitive dependencies. Luckily, an `npm audit fix` seems to resolve those.

### CODE REVIEW

**Comment by alexander-akait** [comment]
Please accept CLA

**Comment by eFrane** [comment]
@alexander-akait Where do I do that?

**Comment by alexander-akait** [comment]
Please use link https://cla.js.foundation/webpack-contrib/css-minimizer-webpack-plugin?pullRequest=107

**Comment by eFrane** [comment]
@alexander-akait Done.

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
